### ISSUE TITLE
please provide release tag

### ISSUE THREAD

**Issue by EricDeveaud** [lucapinello/Haystack#4]
Hello, 

our policy is to install from tagged release versions instead of git clone

this allow us to have some reproductibility among the time.
and's it easier to wget a release tagged archive version than git checkout to some specific comit

hope this will get you atention.

regards

Eric

**Comment by lucapinello** [comment]
Hi Eric, we really value your feedback. We have moved Haystack  on my GitHub lab account https://github.com/pinellolab/haystack_bio and we will provide tags from now on. We also posted a preprint here: https://www.biorxiv.org/content/early/2017/10/05/199067
